Name:           ros-kinetic-py-trees
Version:        0.5.8
Release:        0%{?dist}
Summary:        ROS py_trees package

Group:          Development/Libraries
License:        BSD
URL:            http://py-trees.readthedocs.io
Source0:        %{name}-%{version}.tar.gz

Requires:       pydot
Requires:       python-enum34
BuildRequires:  python-setuptools
BuildRequires:  ros-kinetic-catkin

%description
Pythonic implementation of behaviour trees.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sun Mar 19 2017 Daniel Stonier <d.stonier@gmail.com> - 0.5.8-0
- Autogenerated by Bloom

* Sun Mar 19 2017 Daniel Stonier <d.stonier@gmail.com> - 0.5.7-1
- Autogenerated by Bloom

* Wed Mar 01 2017 Daniel Stonier <d.stonier@gmail.com> - 0.5.7-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Daniel Stonier <stonier@yujinrobot.com> - 0.5.4-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Daniel Stonier <stonier@yujinrobot.com> - 0.5.2-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Daniel Stonier <stonier@yujinrobot.com> - 0.5.1-1
- Autogenerated by Bloom

* Tue Feb 21 2017 Daniel Stonier <stonier@yujinrobot.com> - 0.5.1-0
- Autogenerated by Bloom

